FROM openjdk:17-jdk
#C:\Users\LENOVO\Desktop\App\Appclima\target
ARG JAR_FILE=target C:/Users/LENOVO/Desktop/App/Appclima/target/Appclima-0.0.1-SNAPSHOT.jar 
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
#COPY target C:/Users/LENOVO/Desktop/App/Appclima/target/Appclima-0.0.1-SNAPSHOT.jar 
#COPY target /App/Appclima/target/Appclima-0.0.1-SNAPSHOT.jar app.jar
#ENTRYPOINT ["java", "-jar", "C:/Users/LENOVO/Desktop/App/Appclima/target/Appclima-0.0.1-SNAPSHOT.jar"]




